name: Check YAML

on:
  push:
    branches:
      - main

jobs:
  check_yaml:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # - name: Install dos2unix
      #   run: apt-get install dos2unix

      - name: Check name field in YAML files
        id: check_name
        run: |

          find . -type f \( -name "docker-compose.yaml" -or -name "docker-compose.yml" \) | while read -r file; do
            if ! grep -qP '^name:\s[a-z0-9_-]*\r?$' "$file"; then
              echo "There is a problem with the value of name in the submitted yaml, please make sure the value is in the range [a-z0-9_-]. And error file name $file"
              echo $file
              exit 1
            fi
          done
